export const TILES = {

  TREE_ROUND: [["TREE_ROUND_NW","TREE_ROUND_NE",],["TREE_ROUND_SW","TREE_ROUND_SE",],],
  TREE_SCRUFFY: [["TREE_SCRUFFY_NW","TREE_SCRUFFY_NE",],["TREE_SCRUFFY_SW","TREE_SCRUFFY_SE",],],

  SIGN_WOOD: [["SIGNPOST_WOOD_NW","SIGNPOST_WOOD_NE",],["SIGNPOST_WOOD_WW","SIGNPOST_WOOD_SE",],],

  WATER_FULL: [["WATER_STILL","WATER_STILL",],["WATER_STILL","WATER_STILL",],],
  WATER_EDGE_N: [["WATER_EDGE_S","WATER_EDGE_S",],["WATER_STILL","WATER_STILL",],],
  WATER_EDGE_S: [["WATER_STILL","WATER_STILL",],["WATER_EDGE_S","WATER_EDGE_S",],],
  WATER_EDGE_W: [["WATER_EDGE_W","WATER_STILL",],["WATER_EDGE_W","WATER_STILL",],],
  WATER_EDGE_CORNER_NW: [["WATER_EDGE_CORNER_NW","WATER_EDGE_S",],["WATER_EDGE_W","WATER_STILL",],],
  WATER_EDGE_CORNER_SW: [["WATER_EDGE_W","WATER_STILL",],["WATER_EDGE_CORNER_SW","WATER_EDGE_S",],],
}
